apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: multi-k8s-manikjain-live-tls
spec:
  secretName: multi-k8s-manikjain-live
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s-manikjain.live
  dnsNames:
    - multi-k8s-manikjain.live
    - www.multi-k8s-manikjain.live
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - multi-k8s-manikjain.live
          - www.multi-k8s-manikjain.live